name: build
on: [push, pull_request]
jobs:
  build:
    name: aws-boomer on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, macos-14, windows-latest, ubuntu-latest, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build native executable
        run: |
          ./gradlew nativeCompile

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: aws-boomer-${{ matrix.os }}
          path: build/native/nativeCompile/*